#!/bin/sh

# PROVIDE: jcollectd
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="jcollectd"
rcvar="${name}_enable"
desc="JCollectd java monitoring daemon"
start_cmd="${name}_start"
procname="/usr/local/openjdk8/bin/java"
pidfile="/var/run/${name}.pid"

load_rc_config $name
: ${jcollectd_enable:="NO"}

jcollectd_start()
{
	nohup /usr/local/openjdk8/bin/java -XX:MaxMetaspaceSize=10m -Xms32m -Xmx32m \
		-jar /store/maintenance/JCollectd/JCollectd.jar \
		/store/maintenance/JCollectd/jcollectd.properties > /store/maintenance/JCollectd/jcollectd.log \
		& echo $! > ${pidfile}
}

run_rc_command "$1"
