interval: PT5S
probes:
  - type: load
    size: full
  - type: cpu
    size: half
  - type: mem
    size: half
  - type: net
    size: half
    device: ix0
  - type: disk
    size: half
    device: ada0+ada1+ada2+ada3+ada4+ada5
    label: zstore
