#!/bin/sh

# PROVIDE: jcollectd
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="jcollectd"
rcvar="${name}_enable"
desc="JCollectd java monitoring daemon"
command="/usr/local/openjdk21/bin/java"
start_cmd="${name}_start"
pidfile="/var/run/${name}.pid"
chdir="/store/maintenance/jcollectd"
javaopts="-Xms32m -Xmx32m"

load_rc_config $name
: ${jcollectd_enable:="NO"}

jcollectd_start()
{
        cd ${chdir} && nohup ${command} ${javaopts} -jar jcollectd.jar config.yaml > jcollectd.log & echo $! > ${pidfile}
}

run_rc_command "$1"
